// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgIy6rNA4f5k1bDt96gRgCdqHr3wb9lAU',
    appId: '1:901424431008:web:039dd14fea0c2553e26ec5',
    messagingSenderId: '901424431008',
    projectId: 'authtoba',
    authDomain: 'authtoba.firebaseapp.com',
    storageBucket: 'authtoba.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIvZyLj9WETeGRclL0Qb96qnACgLrKS0s',
    appId: '1:901424431008:android:c9cb348ba36802cbe26ec5',
    messagingSenderId: '901424431008',
    projectId: 'authtoba',
    storageBucket: 'authtoba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuPnyuPkz16wEVMvuODtz4S-M1yh1o_xg',
    appId: '1:901424431008:ios:8062fde65d75706ae26ec5',
    messagingSenderId: '901424431008',
    projectId: 'authtoba',
    storageBucket: 'authtoba.appspot.com',
    iosBundleId: 'com.example.loginRegisterToba',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuPnyuPkz16wEVMvuODtz4S-M1yh1o_xg',
    appId: '1:901424431008:ios:54e74fc56fe309b0e26ec5',
    messagingSenderId: '901424431008',
    projectId: 'authtoba',
    storageBucket: 'authtoba.appspot.com',
    iosBundleId: 'com.example.loginRegisterToba.RunnerTests',
  );
}
